//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlientTest.ServiceGameReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KlientTest.ServiceGameReference.DocumentDoc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KlientTest.ServiceGameReference.DocumentHtml))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KlientTest.ServiceGameReference.DocumentPdf))]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KlientTest.ServiceGameReference.Content ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KlientTest.ServiceGameReference.Content Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Content", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KlientTest.ServiceGameReference.EditableContent))]
    public partial class Content : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocContent {
            get {
                return this.DocContentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocContentField, value) != true)) {
                    this.DocContentField = value;
                    this.RaisePropertyChanged("DocContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentDoc", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    public partial class DocumentDoc : KlientTest.ServiceGameReference.Document {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentHtml", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    public partial class DocumentHtml : KlientTest.ServiceGameReference.Document {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentPdf", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    public partial class DocumentPdf : KlientTest.ServiceGameReference.Document {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditableContent", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    public partial class EditableContent : KlientTest.ServiceGameReference.Content {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KlientTest.ServiceGameReference.EditableField[] EditableFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KlientTest.ServiceGameReference.EditableField[] EditableFields {
            get {
                return this.EditableFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.EditableFieldsField, value) != true)) {
                    this.EditableFieldsField = value;
                    this.RaisePropertyChanged("EditableFields");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditableField", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    [System.SerializableAttribute()]
    public partial class EditableField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KlientTest.ServiceGameReference.FieldType FieldTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KlientTest.ServiceGameReference.FieldType FieldType {
            get {
                return this.FieldTypeField;
            }
            set {
                if ((this.FieldTypeField.Equals(value) != true)) {
                    this.FieldTypeField = value;
                    this.RaisePropertyChanged("FieldType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldType", Namespace="http://schemas.datacontract.org/2004/07/Kontrakt")]
    public enum FieldType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STRING = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NUMBER = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATE = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGameReference.IServiceGame")]
    public interface IServiceGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGame/GetDocumentsList", ReplyAction="http://tempuri.org/IServiceGame/GetDocumentsListResponse")]
        KlientTest.ServiceGameReference.Document[] GetDocumentsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGame/GetDocumentsList", ReplyAction="http://tempuri.org/IServiceGame/GetDocumentsListResponse")]
        System.Threading.Tasks.Task<KlientTest.ServiceGameReference.Document[]> GetDocumentsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGame/AddDocument", ReplyAction="http://tempuri.org/IServiceGame/AddDocumentResponse")]
        void AddDocument(KlientTest.ServiceGameReference.Document newDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGame/AddDocument", ReplyAction="http://tempuri.org/IServiceGame/AddDocumentResponse")]
        System.Threading.Tasks.Task AddDocumentAsync(KlientTest.ServiceGameReference.Document newDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGame/RemoveDocument", ReplyAction="http://tempuri.org/IServiceGame/RemoveDocumentResponse")]
        void RemoveDocument(KlientTest.ServiceGameReference.Document delDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGame/RemoveDocument", ReplyAction="http://tempuri.org/IServiceGame/RemoveDocumentResponse")]
        System.Threading.Tasks.Task RemoveDocumentAsync(KlientTest.ServiceGameReference.Document delDoc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceGameChannel : KlientTest.ServiceGameReference.IServiceGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGameClient : System.ServiceModel.ClientBase<KlientTest.ServiceGameReference.IServiceGame>, KlientTest.ServiceGameReference.IServiceGame {
        
        public ServiceGameClient() {
        }
        
        public ServiceGameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KlientTest.ServiceGameReference.Document[] GetDocumentsList() {
            return base.Channel.GetDocumentsList();
        }
        
        public System.Threading.Tasks.Task<KlientTest.ServiceGameReference.Document[]> GetDocumentsListAsync() {
            return base.Channel.GetDocumentsListAsync();
        }
        
        public void AddDocument(KlientTest.ServiceGameReference.Document newDoc) {
            base.Channel.AddDocument(newDoc);
        }
        
        public System.Threading.Tasks.Task AddDocumentAsync(KlientTest.ServiceGameReference.Document newDoc) {
            return base.Channel.AddDocumentAsync(newDoc);
        }
        
        public void RemoveDocument(KlientTest.ServiceGameReference.Document delDoc) {
            base.Channel.RemoveDocument(delDoc);
        }
        
        public System.Threading.Tasks.Task RemoveDocumentAsync(KlientTest.ServiceGameReference.Document delDoc) {
            return base.Channel.RemoveDocumentAsync(delDoc);
        }
    }
}
